### ISSUE TITLE
邮件里的再提一次.

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-1#1]
邮件里已经提过了, 这里再提一次.
上次邮件交流了一下关于第一次任务的事情, 有两位童鞋没有回信, 不知道是不是没看到邮件. 
根据回信, 每个人各自的任务安排是这样的.

zhe13: 3 - 4 - 5 - 7 - 8 - 9 - 10 - 11
Fiooona: 3 - 4 - 5 - 7 - 8 - 9
theJian: 7 - 8 - 9 - 10 - 12

合作模式: 每个人各自分一个branch开展任务, master 作为最终团队成品. 每次发生 merge 既是一次团队内的 code review, 最后麻烦 zhe13 将最后的结果 push 到 ife 的仓库.

 注意事项: 
- 如果需要 merge 请使用 pull request, 这样好进行 code review.
- 没事常merge, 少量多次, 保证一次review的代码量不要太大.
- 多个人领取了一样的任务时, 注意相互沟通, 协调好merge的先后顺序, 不要产生太多需要手动解决的代码冲突.
- 每次的merge都是一次团队内的code review, 所有人都应该参与.
- 大家都很忙, 注意自己把握时间, 本次的截至时间是 4 月 3 日, 今天是 3 月 15 日.

最后, 那两位童鞋看到了请说一声, 我们需要确定团队人数.

差点忘了, 关于整个工程目录, 目前的想法是 一个任务一个文件夹, 文件夹名为两位任务编号. 比如我的任务是 7 - 8 - 9 - 10 - 12, 那我的branch下目录应该有5个文件夹, 分别为 07, 08, 08, 10, 12. 大家有什么想法吗?

**Comment by theJian** [comment]
如果有任何修改意见或者补充, 请在下面提出.

**Comment by zhe13** [comment]
@pollyu522 最近在做Arduino交互装置，考虑到她本身前端专业毕业，task1她和我提交一份。没错就是上面最长的那个路线。

**Comment by Fiooona** [comment]
感觉好像懂了。。没有意见，看来 zhe13 和pollyu522 私交甚好
