### ISSUE TITLE
Task10 Question

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#11]
# 解题思路

 Q1:align-items:center ＋ justify-content:space-between.

 Q2: media querry + wrap => blue{order;-1} + align-items:flex-start + justify-content:space-between + align-content:space－between;
# Issues
- :我在侧轴方向上的aligncontent没有任何作用
- ![align-items](http://cdn2.w3cplus.com/cdn/farfuture/oOEDDXBpXz5MYc-eOv0cCQUm9wtOhlENiGMMUUM3d88/mtime:1421035113/sites/default/files/styles/print_image/public/blogs/2013/flexbox-basics-4.jpg)
  珍视测试情况，baseline等同于flexend。strech没有拉伸

**Comment by zhe13** [comment]
@theJian

**Comment by zhe13** [comment]
#Flexbox 布局和网格布局的异同

 ？

 #以及分别适用于什么样的场景

 ？
 #MARKS
- 大多数的Flexbox属性都应用于父容器的元素上
- flex-flow equals to flex-direction plus flex-wrap
- justify-content:决定了主轴的排列情况
- align-items:决定了主轴元素对侧轴的依靠情况
- align-content:决定侧轴（多行）的排列情况
  
  #Questions
- ![align-items](http://cdn2.w3cplus.com/cdn/farfuture/oOEDDXBpXz5MYc-eOv0cCQUm9wtOhlENiGMMUUM3d88/mtime:1421035113/sites/default/files/styles/print_image/public/blogs/2013/flexbox-basics-4.jpg)
  测试情况，baseline等同于flexend。strech没有拉伸？
  
  #解题思路
  Q1:align-items:center ＋ justify-content:space-between.
  
  Q2: media querry + wrap => blue{order;-1} + align-items:flex-start + justify-content:space-between + align-content:

**Comment by zhe13** [comment]
##Flexbox 布局和网格布局的异同

？

---

##以及分别适用于什么样的场景

？

**Comment by theJian** [comment]
:我在侧轴方向上的aligncontent没有任何作用

什么意思？没听懂

**Comment by zhe13** [comment]
给你([传送门](http://zhe13.top/ife/ife-task-1/10/10.html)。

**Comment by theJian** [comment]
你是不是说没有竖直居中？

**Comment by zhe13** [comment]
align-content明显对应侧轴（这里竖直）方向居中，我怎么弄都没反应

**Comment by theJian** [comment]
:disappointed: 你看看你的 container 的高度

**Comment by zhe13** [comment]
卧槽，flex不是弹性盒吗，不是默认100%？

**Comment by theJian** [comment]
Flexbox 可以实现网格布局， 有个框架叫 grid 好像， 就是基于flexbox的
