### ISSUE TITLE
关于 CSS :nth-child() 选择器

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-1#3]
在 task 12 第一个任务中要求表格前三行特殊表示.
我是这样做的.

```
tbody tr:nth-child(-n+3) {
  ...
}
```

不过在此之前我是这样写的 `tbody tr:nth-child(3-n)`, 并没有生效.
真是很奇怪.
是我喝多了:question:

**Comment by zhe13** [comment]
这个问题我好像以前遇到过，tbody中有两个隐藏的东西，你去w3c查查看，这东西十分的诡异。btw，我刚刚亲妈爆炸了，正在上传，断电了。比以往早了四分钟。下楼喝了酒上来，简直

**Comment by theJian** [comment]
http://stackoverflow.com/questions/36025729/different-between-nth-child-n3-and-nth-child3-n
