### ISSUE TITLE
新任务来了==

### ISSUE THREAD

**Issue by Fiooona** [DieInGame/ife-task-1#30]
有新任务了，新任务要新建一个仓库还是继续用这个仓库？(http://ife.baidu.com/task/all)
Task9 要不要分工？还是每人都写？

**Comment by zhe13** [comment]
写了一下午开题报告，莫慌，开新的

**Comment by theJian** [comment]
天那, 我脑袋上锅好多, 好沉, 宝宝心里苦

**Comment by zhe13** [comment]
@Fiooona 师姐等我。我先把除9外的所有今天刷完
