### ISSUE TITLE
所有master的代码都会在我的服务器上

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#31]
地址列在了github项目标题边上。
提出需要merge的分支我会把服务器部署分支切到需要merge的分支上，这样方便大家在线预览。
考虑到大家课程忙碌程度不一致，每次Review有两个人通过我们就Merge。
Review分支在服务器上的存在时间是一天／除非下一个需要review的对象出现。

**Comment by theJian** [comment]
我一般是切分支进行预览的, 这个就是不 fork 的原因( 我不得不 clone fork 的 repo 来进行预览)
