### ISSUE TITLE
7 & 9

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#32]
7 & 9页面好复杂。
老司机准备开车，有谁和我分任务做的吗就是 7上 9下我 ，7 下9上你。

**Comment by zhe13** [comment]
那啥当我放屁＝－＝。设计稿里面的图片可以随便替代的

**Comment by Fiooona** [comment]
我把7的上半部分也写完了，你把图片给换了？==我直接下载别的组里的images文件。。

**Comment by zhe13** [comment]
哎呀我也刚做到新世界＝－＝。。。。。。我们9⃣️分工吧。。。

**Comment by zhe13** [comment]
我自己找的图＝－＝。。。。

**Comment by Fiooona** [comment]
整体页面布局，整个顶部，右侧的面包屑，及右侧中间的两个第一组项目
整个左侧
右侧上面的前三部分：查询选项部分，价格显示部分，4月统计部分
右侧下方的2个模块，日历及表格

这4部分，你选两个

**Comment by zhe13** [comment]
像我这么被动的人，我就选下面两个好了😊

**Comment by Fiooona** [comment]
好啊~ 吃饭去啦，

**Comment by theJian** [comment]
7和9你们开分支吧, 我有时间可以来写点, 如果有时间的话
