### ISSUE TITLE
你们都走了，Task9 我就自己填坑吧。

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#39]
狗逼们＝－＝。
虽然我在辛苦的填坑，但是谁告诉我table单元格的border之间如何取消间隙啊。
快告诉我＝－＝ 我还要背GRE的。。。。

**Comment by Fiooona** [comment]
border-collapse:collapse;?是这个嘛? 不太理解

**Comment by zhe13** [comment]
原来是border 折叠属性

**Comment by zhe13** [comment]
爱呀＝－＝我就真是日狗了。师姐怎么才能在CSS里加循环和遍历啊＝－＝我要变量我要变量！！！！！

**Comment by theJian** [comment]
I use Sass

**Comment by theJian** [comment]
Sass 或 Less, 拯救你被 CSS 摧毁的人生
