### ISSUE TITLE
Some new way to achieve assignment3

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#5]
> 关于三栏布局，我们都比较熟悉**_浮动法**_和**_绝对定位法**_。
> 就和ife中介绍的position和float一样，但是我在亲妈爆炸断电黑屏之前发现了一个新的办法十分诡异。
> margin负值，使用一个容器包裹目标对象，我之后会放链接进来

**Comment by theJian** [comment]
说好的新方法呢?怎么close了.
