### ISSUE TITLE
task 12 进行 review 和下一个task的协调

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-1#8]
task 12 全部完成请review, 特别是 @satansk 童鞋你也选了这个吧, 之前忘了和你协调了 :fearful: , 你 review 一下 code 吧, 看看是否存在问题/bug/改进.

review 结束后吼一声, zhe13童鞋会去提交task 12了.

我现在开始做task 10, @zhe13 我们协调一下?

**Comment by zhe13** [comment]
task10?
好的我开始了

**Comment by kun-song** [comment]
task 12 你们 review 完了就提交吧，我虽然选了但是做的速度比较慢，后面我再研究下。
