### ISSUE TITLE
Task3 的一些看法

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-1#9]
## margin负值法

> 这种方法是在实际的网站中应用的最多的，感觉多少有些跟风的嫌疑,但我本人完全没用过这个方法。此方法很难用一句话概括。首先，中间的主体要使用双层标签。外层div宽度100%显示，并且浮动（本例左浮动，下面所述依次为基础），内层div为真正的主体内容，含有左右210像素的margin值。左栏与右栏都是采用margin负值定位的，左栏左浮动，margin-left为-100%，由于前面的div宽度100%与浏览器，所以这里的-100%margin值正好使左栏div定位到了页面的左侧；右侧栏也是左浮动，其margin-left也是负值，大小为其本身的宽度即200像素。

![CSS](http://image.zhangxinxu.com/image/blog/200911/2009-11-17_194544.png)

![HTML](http://image.zhangxinxu.com/image/blog/200911/2009-11-17_194614.png)

**Comment by zhe13** [comment]
@theJian 在这里

**Comment by theJian** [comment]
很有意思的一种实现法.
大家可以看这里方便理解.

<p data-height="268" data-theme-id="0" data-slug-hash="bpBPya" data-default-tab="result" data-user="theJian" class="codepen">See the Pen <a href="http://codepen.io/theJian/pen/bpBPya/">bpBPya</a> by theJian (<a href="http://codepen.io/theJian">@theJian</a>) on <a href="http://codepen.io">CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
